/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as SubscriptionRouteImport } from './routes/subscription'
import { Route as StackBuilderRouteImport } from './routes/stack-builder'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RankingsRouteImport } from './routes/rankings'
import { Route as PromptsRouteImport } from './routes/prompts'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FinderRouteImport } from './routes/finder'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as CalculatorRouteImport } from './routes/calculator'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as AuthCallbackRouteImport } from './routes/auth-callback'
import { Route as AppBuildersRouteImport } from './routes/app-builders'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StacksIndexRouteImport } from './routes/stacks.index'
import { Route as StacksIdRouteImport } from './routes/stacks.$id'
import { Route as ApiStripeWebhookRouteImport } from './routes/api.stripe-webhook'
import { Route as AdminRevenueRouteImport } from './routes/admin.revenue'
import { Route as AdminAuthDiagnosticsRouteImport } from './routes/admin.auth-diagnostics'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionRoute = SubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const StackBuilderRoute = StackBuilderRouteImport.update({
  id: '/stack-builder',
  path: '/stack-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingsRoute = RankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptsRoute = PromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FinderRoute = FinderRouteImport.update({
  id: '/finder',
  path: '/finder',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorRoute = CalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth-callback',
  path: '/auth-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppBuildersRoute = AppBuildersRouteImport.update({
  id: '/app-builders',
  path: '/app-builders',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StacksIndexRoute = StacksIndexRouteImport.update({
  id: '/stacks/',
  path: '/stacks/',
  getParentRoute: () => rootRouteImport,
} as any)
const StacksIdRoute = StacksIdRouteImport.update({
  id: '/stacks/$id',
  path: '/stacks/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe-webhook',
  path: '/api/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRevenueRoute = AdminRevenueRouteImport.update({
  id: '/admin/revenue',
  path: '/admin/revenue',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthDiagnosticsRoute = AdminAuthDiagnosticsRouteImport.update({
  id: '/admin/auth-diagnostics',
  path: '/admin/auth-diagnostics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/agents': typeof AgentsRoute
  '/app-builders': typeof AppBuildersRoute
  '/auth-callback': typeof AuthCallbackRoute
  '/billing': typeof BillingRoute
  '/calculator': typeof CalculatorRoute
  '/community': typeof CommunityRoute
  '/compare': typeof CompareRoute
  '/dashboard': typeof DashboardRoute
  '/finder': typeof FinderRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/prompts': typeof PromptsRoute
  '/rankings': typeof RankingsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/stack-builder': typeof StackBuilderRoute
  '/subscription': typeof SubscriptionRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/auth-diagnostics': typeof AdminAuthDiagnosticsRoute
  '/admin/revenue': typeof AdminRevenueRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/stacks/$id': typeof StacksIdRoute
  '/stacks/': typeof StacksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/agents': typeof AgentsRoute
  '/app-builders': typeof AppBuildersRoute
  '/auth-callback': typeof AuthCallbackRoute
  '/billing': typeof BillingRoute
  '/calculator': typeof CalculatorRoute
  '/community': typeof CommunityRoute
  '/compare': typeof CompareRoute
  '/dashboard': typeof DashboardRoute
  '/finder': typeof FinderRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/prompts': typeof PromptsRoute
  '/rankings': typeof RankingsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/stack-builder': typeof StackBuilderRoute
  '/subscription': typeof SubscriptionRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/auth-diagnostics': typeof AdminAuthDiagnosticsRoute
  '/admin/revenue': typeof AdminRevenueRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/stacks/$id': typeof StacksIdRoute
  '/stacks': typeof StacksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/agents': typeof AgentsRoute
  '/app-builders': typeof AppBuildersRoute
  '/auth-callback': typeof AuthCallbackRoute
  '/billing': typeof BillingRoute
  '/calculator': typeof CalculatorRoute
  '/community': typeof CommunityRoute
  '/compare': typeof CompareRoute
  '/dashboard': typeof DashboardRoute
  '/finder': typeof FinderRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/prompts': typeof PromptsRoute
  '/rankings': typeof RankingsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/stack-builder': typeof StackBuilderRoute
  '/subscription': typeof SubscriptionRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/auth-diagnostics': typeof AdminAuthDiagnosticsRoute
  '/admin/revenue': typeof AdminRevenueRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/stacks/$id': typeof StacksIdRoute
  '/stacks/': typeof StacksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/agents'
    | '/app-builders'
    | '/auth-callback'
    | '/billing'
    | '/calculator'
    | '/community'
    | '/compare'
    | '/dashboard'
    | '/finder'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/profile'
    | '/prompts'
    | '/rankings'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/stack-builder'
    | '/subscription'
    | '/verify-email'
    | '/admin/analytics'
    | '/admin/auth-diagnostics'
    | '/admin/revenue'
    | '/api/stripe-webhook'
    | '/stacks/$id'
    | '/stacks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/agents'
    | '/app-builders'
    | '/auth-callback'
    | '/billing'
    | '/calculator'
    | '/community'
    | '/compare'
    | '/dashboard'
    | '/finder'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/profile'
    | '/prompts'
    | '/rankings'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/stack-builder'
    | '/subscription'
    | '/verify-email'
    | '/admin/analytics'
    | '/admin/auth-diagnostics'
    | '/admin/revenue'
    | '/api/stripe-webhook'
    | '/stacks/$id'
    | '/stacks'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/agents'
    | '/app-builders'
    | '/auth-callback'
    | '/billing'
    | '/calculator'
    | '/community'
    | '/compare'
    | '/dashboard'
    | '/finder'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/profile'
    | '/prompts'
    | '/rankings'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/stack-builder'
    | '/subscription'
    | '/verify-email'
    | '/admin/analytics'
    | '/admin/auth-diagnostics'
    | '/admin/revenue'
    | '/api/stripe-webhook'
    | '/stacks/$id'
    | '/stacks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AgentsRoute: typeof AgentsRoute
  AppBuildersRoute: typeof AppBuildersRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  BillingRoute: typeof BillingRoute
  CalculatorRoute: typeof CalculatorRoute
  CommunityRoute: typeof CommunityRoute
  CompareRoute: typeof CompareRoute
  DashboardRoute: typeof DashboardRoute
  FinderRoute: typeof FinderRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ProfileRoute: typeof ProfileRoute
  PromptsRoute: typeof PromptsRoute
  RankingsRoute: typeof RankingsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  StackBuilderRoute: typeof StackBuilderRoute
  SubscriptionRoute: typeof SubscriptionRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAuthDiagnosticsRoute: typeof AdminAuthDiagnosticsRoute
  AdminRevenueRoute: typeof AdminRevenueRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  StacksIdRoute: typeof StacksIdRoute
  StacksIndexRoute: typeof StacksIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscription': {
      id: '/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof SubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stack-builder': {
      id: '/stack-builder'
      path: '/stack-builder'
      fullPath: '/stack-builder'
      preLoaderRoute: typeof StackBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings': {
      id: '/rankings'
      path: '/rankings'
      fullPath: '/rankings'
      preLoaderRoute: typeof RankingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompts': {
      id: '/prompts'
      path: '/prompts'
      fullPath: '/prompts'
      preLoaderRoute: typeof PromptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finder': {
      id: '/finder'
      path: '/finder'
      fullPath: '/finder'
      preLoaderRoute: typeof FinderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth-callback': {
      id: '/auth-callback'
      path: '/auth-callback'
      fullPath: '/auth-callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app-builders': {
      id: '/app-builders'
      path: '/app-builders'
      fullPath: '/app-builders'
      preLoaderRoute: typeof AppBuildersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stacks/': {
      id: '/stacks/'
      path: '/stacks'
      fullPath: '/stacks/'
      preLoaderRoute: typeof StacksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stacks/$id': {
      id: '/stacks/$id'
      path: '/stacks/$id'
      fullPath: '/stacks/$id'
      preLoaderRoute: typeof StacksIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe-webhook': {
      id: '/api/stripe-webhook'
      path: '/api/stripe-webhook'
      fullPath: '/api/stripe-webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/revenue': {
      id: '/admin/revenue'
      path: '/admin/revenue'
      fullPath: '/admin/revenue'
      preLoaderRoute: typeof AdminRevenueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/auth-diagnostics': {
      id: '/admin/auth-diagnostics'
      path: '/admin/auth-diagnostics'
      fullPath: '/admin/auth-diagnostics'
      preLoaderRoute: typeof AdminAuthDiagnosticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AgentsRoute: AgentsRoute,
  AppBuildersRoute: AppBuildersRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  BillingRoute: BillingRoute,
  CalculatorRoute: CalculatorRoute,
  CommunityRoute: CommunityRoute,
  CompareRoute: CompareRoute,
  DashboardRoute: DashboardRoute,
  FinderRoute: FinderRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ProfileRoute: ProfileRoute,
  PromptsRoute: PromptsRoute,
  RankingsRoute: RankingsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  StackBuilderRoute: StackBuilderRoute,
  SubscriptionRoute: SubscriptionRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAuthDiagnosticsRoute: AdminAuthDiagnosticsRoute,
  AdminRevenueRoute: AdminRevenueRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  StacksIdRoute: StacksIdRoute,
  StacksIndexRoute: StacksIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
